version: '3'
services:
  codingdojos:
    build: .
    ports:
      - 8080:8080
    environment:
      - ARTIFACTORY_URL=http://10.0.4.44:8081
      - SPRING_DATA_MONGODB_HOST=mongo-db
  mongo-db:
    image: "mongo:4.2"

