application:
  name: ${APP_NAME:serli.codingdojos}
  env: ${APP_ENV:dev}
  client:
    location: ${CLIENT_LOCATION:http://localhost:1234}
    from-parcel: ${FROM_PARCEL:false}

logging.level:
  root: INFO

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 976098152567-a7qni0u47qsfaojmt585cbekooo19vub.apps.googleusercontent.com
            client-secret: G0mLlmNRU7hhpquXHT0LMLds

profile:
  user:
    admin: vincent.gouadon@serli.com,quentin.proust@serli.com
    vip: sylvie.colas1@gmail.com

sponsored:
  public-key: ${SPONSORED_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo6DqsEMywYBMoOdNEN0KfrPhOgqYTVqikHBrfo7oIoA1ZYVbMqtSpagQv+XXM/YinfDlMfmE7rD6ktS9ttooDBO2T0eXagRxAGQpcRKgKgy5KbuozST0C6TPFIU2prDG40kSlP1ev21eKWaIhP+limhtySklXj1wdRs4i31kVSpao0LBbt/N6PdwsQBQUyx/6QhxU+0HMYYu/Q15zWcGYlmQy6qSudi8MQvvDXV2jNgEylmGRAEvg3dgtlWAumrnsML7f6tD1lXxrnJRLLY+LsDWEB4A28W0xVIH+iUmVG+brKd+Y2HVwuYQqLqsX1uiZLAnFlbtrp+QA1jVunfH4QIDAQAB}
  private-key: ${SPONSORED_PRIVATE_KEY:MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCjoOqwQzLBgEyg500Q3Qp+s+E6CphNWqKQcGt+jugigDVlhVsyq1KlqBC/5dcz9iKd8OUx+YTusPqS1L222igME7ZPR5dqBHEAZClxEqAqDLkpu6jNJPQLpM8UhTamsMbjSRKU/V6/bV4pZoiE/6WKaG3JKSVePXB1GziLfWRVKlqjQsFu383o93CxAFBTLH/pCHFT7Qcxhi79DXnNZwZiWZDLqpK52LwxC+8NdXaM2ATKWYZEAS+Dd2C2VYC6auewwvt/q0PWVfGuclEstj4uwNYQHgDbxbTFUgf6JSZUb5usp35jYdXC5hCouqxfW6JksCcWVu2un5ADWNW6d8fhAgMBAAECggEAHIUswuJDk4SoVpdaUGkmriTuSe6U007L7P8bTWjdPz43kGVpGvDPq/4aRUhrdSwepobZfBdwuyXv1u3rz1ZBCrHY4gKpepohlB7hNks3zXyAPazu5CrfurPUQFBj0TQYxn7zFTMAc789XVv4ya3Bjdlb4Wchk0aENnUzKuUFOu6qioImZw8HydoDexu0tVLhb2efFPygdgSo8uEXp0LED1iaQL+yffQTRXg2OksXGzDhZIvG/c1M01Bv+dJBGvs8tEVwjvUTxrFKkYXFS/LUJpKUd8x5tkHYpVvuv2xyKwuD6Fb5NhnKLU3Jw0JVUluxbvvAnuERhknaGB4ev9xHUQKBgQDVdv1zIrn997Hjis3mRnNfoYZpFAiKxiXWwbfeX3E6/8MPdPsfLDb1r+XHQQZ+S5PyARNzfKrODd9GrI6a039z6dvImS2wtNetnIjmKgaAwLp7L6bkCnNBW7o5rPgixW+IRNsazRyTsLgk5uj4PoSha2Z1GY7/22oQ9CZOAMgn7QKBgQDEO72+gRhTBtAiESvaGomZEVyj0AYR6IQodkYy62J68yVciDE0iqN5PefK6pdpmmT7YTGOKQUmQiH9WK4/Z+6Hk6skMJyTNAaKd4PsSHLqG7FwZ70oXYMm5Z/fFErllY0nVP+QLt3TUGpRHuO7PU0oq7gwo8tN01AFtHNj7355RQKBgQDK8Am6SNxrru0GdvKSpo2O7//Zq/sG+6QDjD1igngib/6glkUbeKxzXJtll9M1hGKNYyp705yKsrN+/BPC66kyqLSS+9VtNjAJVFTuBCwUgaWH8WCHUcwK6cqchG2OmQcUlOl8jF1Lp2kZZBE92Cm9UF6imv7RDWbD4Wj9JU8kbQKBgQCw4ChnTnVeYQW5r0CXltPv5HZcMWVHPw3gartbqk9aA0/p19iCQ3SWE/aaMFnKFiBvdWv1d4PsuC9q7EQjYsrd6XyZYje/d2Vt6cw/bg4mdk+5wcf+WkudA9zWdrQLvIE+sp6ol5XaouExvWYHn3ms7xtWvEzEGXRHsB9SNM0LAQKBgQCCrvgOSpNT8EyOSXYgQCo8v2VPkgy+NRh5Mi37R2HJVjPy8zG9qAnsUre1PhrwjpIbhuVOPWGUpOA8vgsGu9s05RaYAj7JSkODz1YR1+n9f0pJkg1v46B6pvJc9sMgWukqKVUilvbH6G6HPPrvCU09NO5OGFe45Jhmk3mkgYzoxw==}

